version: '3'
services:
    server:
        build: ./server
        ports:
            - '3000:3000'
    client:
        build: ./src
        ports:
            - '5000:5000'
    db: &postgres
        container_name: postgres
        image: postgres:11.5
        env_file:
            - .env
            - .env.local
        volumes:
            - ./server/pgdata:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        restart: unless-stopped

volumes:
    postgres:
