version: '3'
services:
    backend:
        build:
            context: .
            dockerfile: ./server/Dockerfile
        container_name: backend
        command: npm run start-server
        volumes:
            - .:/backend
        env_file:
            - .env
            - .env.local
        ports:
            - '3000:3000'
    frontend:
        build:
            context: .
            dockerfile: ./src/Dockerfile
        container_name: frontend
        command: npm run start
        volumes:
            - .:/frontend
        env_file:
            - .env
            - .env.local
        ports:
            - '5000:5000'
    db: &postgres
        container_name: postgres
        image: postgres:11.5
        env_file:
            - .env
            - .env.local
        volumes:
            - ./server/pgdata:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        restart: unless-stopped

volumes:
    postgres:
